"""empty message

Revision ID: 78a52a1d1d4f
Revises: 5ca9fab29c11
Create Date: 2023-01-17 16:25:02.351878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a52a1d1d4f'
down_revision = '5ca9fab29c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('height', sa.String(length=32), nullable=False),
    sa.Column('hair_color', sa.String(length=32), nullable=False),
    sa.Column('eyes_color', sa.String(length=32), nullable=False),
    sa.Column('skin_color', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('population', sa.String(length=64), nullable=False),
    sa.Column('terrain', sa.String(length=32), nullable=False),
    sa.Column('climate', sa.String(length=64), nullable=False),
    sa.Column('diameter', sa.String(length=64), nullable=False),
    sa.Column('orbital_period', sa.String(length=32), nullable=False),
    sa.Column('rotation_period', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('climate'),
    sa.UniqueConstraint('diameter'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('population')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id'),
    sa.UniqueConstraint('planet_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
