"""empty message

Revision ID: a7e8cefe6ae0
Revises: c6a6de14fe63
Create Date: 2023-01-17 19:29:25.769151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e8cefe6ae0'
down_revision = 'c6a6de14fe63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_planets', schema=None) as batch_op:
        batch_op.drop_constraint('user_favorite_planets_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_favorite_planets_user_id_key', ['user_id'])

    # ### end Alembic commands ###
