"""empty message

Revision ID: d27152056895
Revises: a7e8cefe6ae0
Create Date: 2023-01-17 19:40:32.231914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27152056895'
down_revision = 'a7e8cefe6ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint('planet_climate_key', type_='unique')
        batch_op.drop_constraint('planet_diameter_key', type_='unique')
        batch_op.drop_constraint('planet_name_key', type_='unique')
        batch_op.drop_constraint('planet_population_key', type_='unique')

    with op.batch_alter_table('user_favorite_characters', schema=None) as batch_op:
        batch_op.drop_constraint('user_favorite_characters_fav_character_id_key', type_='unique')
        batch_op.drop_constraint('user_favorite_characters_user_id_key', type_='unique')

    with op.batch_alter_table('user_favorite_planets', schema=None) as batch_op:
        batch_op.drop_constraint('user_favorite_planets_fav_planet_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_favorite_planets_fav_planet_id_key', ['fav_planet_id'])

    with op.batch_alter_table('user_favorite_characters', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_favorite_characters_user_id_key', ['user_id'])
        batch_op.create_unique_constraint('user_favorite_characters_fav_character_id_key', ['fav_character_id'])

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.create_unique_constraint('planet_population_key', ['population'])
        batch_op.create_unique_constraint('planet_name_key', ['name'])
        batch_op.create_unique_constraint('planet_diameter_key', ['diameter'])
        batch_op.create_unique_constraint('planet_climate_key', ['climate'])

    # ### end Alembic commands ###
